folders:
  - path: '../algorithms/term1'
  - path: '../algorithms/term2'
  - path: '../applied-math/term4'
  - path: '../applied-math/term5'
  - path: '../db/term4'
  - path: '../digital-culture/term1'
  - path: '../discrete-math/term1'
  - path: '../discrete-math/term2'
  - path: '../ecm/term1'
  - path: '../linear-algebra/term1'
  - path: '../linear-algebra/term2'
  - path: '../ml/term5'
  - path: '../life-safety/term3'
  - path: '../uml/term6'
  - path: '../telecom/term6'
  - path: '../windows/term5'
  - path: '../info-sys/term6'
  - path: '../oop/term3'
    tree_args: '-L 1'
  - path: '../os/term3'
    tree_args: '-L 1'
  - path: '../tech/term4'
    tree_args: '-L 1'
    header: |
      ### Solutions

      - `Languages interop`, `FP in F#, Scala`, `Package management`, `Benchmarking`, `Code analysis` using `dotMemory`, `dotTrace`
      - `Java server`, `Anltr parser`, `C# client`, `Roslyn API`
      - `Codeanalyzer` for inverting `if statement`, for detecting unused `private fields`
      - `Distributed file system`
  - path: '../english/term1'
  - path: '../english/term2'
  - path: '../english/term3'
  - path: '../english/term4'
  - path: '../english/term5'
  - path: '../english/term6'
  - path: '../physics/term2'
  - path: '../physics/term3'
  - path: '../physics/term4'
  - path: '../programming/term1'
  - path: '../programming/term2'
  - path: '../.'
    tree_args: '-L 2'
    header: |
      <p align="center">
          <img src="https://count.getloli.com/get/@fadyat?theme=gelbooru" alt="fadyat" width="300px"/>
      </p>

      Repository contains solutions to all the laboratory works for each subject of each semester
      of the "Information Systems and Technologies" program at ITMO University üìö‚ú®

      Your support makes a difference! Don't hesitate to click the star ‚≠êÔ∏è
      
      It would be great to see that my efforts are not in vain ü•∫
    tail: |
      <a href="https://star-history.com/#fadyat/ITMO-PROBLEMS&Date">
        <picture>
          <source media="(prefers-color-scheme: dark)" srcset="https://api.star-history.com/svg?repos=fadyat/ITMO-PROBLEMS&type=Date&theme=dark" />
          <source media="(prefers-color-scheme: light)" srcset="https://api.star-history.com/svg?repos=fadyat/ITMO-PROBLEMS&type=Date" />
          <img alt="Star History Chart" src="https://api.star-history.com/svg?repos=fadyat/ITMO-PROBLEMS&type=Date" />
        </picture>
      </a>
  - path: "../README_RU.md"
    tree_args: '-L 2'
    header: |
      <p align="center">
          <img src="https://count.getloli.com/get/@fadyat?theme=gelbooru" alt="fadyat" width="300px"/>
      </p>

      –†–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π —Å–æ–¥–µ—Ä–∂–∏—Ç —Ä–µ—à–µ–Ω–∏—è –ª–∞–±–æ—Ä–∞—Ç–æ—Ä–Ω—ã—Ö —Ä–∞–±–æ—Ç –ø–æ –≤—Å–µ–º –ø—Ä–µ–¥–º–µ—Ç–∞–º –∫–∞–∂–¥–æ–≥–æ —Å–µ–º–µ—Å—Ç—Ä–∞
      –ø—Ä–æ–≥—Ä–∞–º–º—ã "–ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏–æ–Ω–Ω—ã–µ —Å–∏—Å—Ç–µ–º—ã –∏ —Ç–µ—Ö–Ω–æ–ª–æ–≥–∏–∏" –≤ –£–Ω–∏–≤–µ—Ä—Å–∏—Ç–µ—Ç–µ –ò–¢–ú–û üìö‚ú®
      
      –ù–µ —Å—Ç–µ—Å–Ω—è–π—Ç–µ—Å—å –Ω–∞–∂–∏–º–∞—Ç—å –Ω–∞ –∑–≤–µ–∑–¥–æ—á–∫—É, –µ—Å–ª–∏ —è –≤–∞–º –¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª—å–Ω–æ –ø–æ–º–æ–≥! ‚≠êÔ∏è
      
      –ë—ã–ª–æ –±—ã –∑–¥–æ—Ä–æ–≤–æ —É–≤–∏–¥–µ—Ç—å, —á—Ç–æ –º–æ–∏ —Ç—Ä—É–¥—ã –Ω–µ –ø—Ä–æ—Ö–æ–¥—è—Ç –∑—Ä—è ü•∫
    tail: |
      <a href="https://star-history.com/#fadyat/ITMO-PROBLEMS&Date">
        <picture>
          <source media="(prefers-color-scheme: dark)" srcset="https://api.star-history.com/svg?repos=fadyat/ITMO-PROBLEMS&type=Date&theme=dark" />
          <source media="(prefers-color-scheme: light)" srcset="https://api.star-history.com/svg?repos=fadyat/ITMO-PROBLEMS&type=Date" />
          <img alt="Star History Chart" src="https://api.star-history.com/svg?repos=fadyat/ITMO-PROBLEMS&type=Date" />
        </picture>
      </a>
  - path: '../.practice'
    header: This is a practice reports while learning at the ITMO University.
